# Generated by Django 4.2.27 on 2026-01-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cotisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mois", models.CharField(max_length=50)),
                ("annee", models.IntegerField()),
                ("mananga_paye", models.BooleanField(default=False)),
                (
                    "mananga_montant",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("mananga_date", models.DateField(blank=True, null=True)),
                ("prodiges_paye", models.BooleanField(default=False)),
                (
                    "prodiges_montant",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("prodiges_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["annee", "id"],
                "unique_together": {("mois", "annee")},
            },
        ),
    ]
